<?php $title = $title ?? 'Two-Factor Authentication'; ?>
<div class="ck-bg-white ck-rounded-lg ck-shadow ck-p-6 ck-max-w-2xl">
    <div class="ck-flex ck-justify-between ck-items-center ck-mb-6">
        <h3 class="ck-text-xl ck-font-bold">Two-Factor Authentication</h3>
        <a href="/admin/security" class="ck-text-sm ck-text-blue-600 hover:ck-underline">Back to Security</a>
    </div>

    <?php if ($user && !empty($user->totp_secret)): ?>
        <div class="ck-bg-green-50 ck-border ck-border-green-300 ck-text-green-800 ck-rounded ck-p-4 ck-mb-6">
            <p class="ck-font-medium">Two-factor authentication is enabled.</p>
            <p class="ck-text-sm ck-mt-1">Your account now requires a 6-digit authenticator code on login.</p>
        </div>

        <form method="post" action="/admin/security/2fa/disable" onsubmit="return confirm('Disable two-factor authentication on this account?');">
            <?= csrf_field() ?>
            <button type="submit" class="ck-px-4 ck-py-2 ck-bg-red-600 ck-text-white ck-rounded hover:ck-bg-red-700">Disable 2FA</button>
        </form>
    <?php else: ?>
        <p class="ck-text-gray-600 ck-mb-4">Scan the provisioning URI into your authenticator app (Google Authenticator, Authy, 1Password, etc.)</p>

        <div class="ck-bg-gray-50 ck-p-4 ck-rounded ck-mb-6">
            <label class="ck-block ck-text-sm ck-font-medium ck-text-gray-700 ck-mb-2">Setup code (base32 secret)</label>
            <code class="ck-text-sm ck-break-all"><?= esc($secret) ?></code>
        </div>

        <div class="ck-bg-gray-50 ck-p-4 ck-rounded ck-mb-6">
            <label class="ck-block ck-text-sm ck-font-medium ck-text-gray-700 ck-mb-2">Authenticator URI</label>
            <code class="ck-text-xs ck-break-all"><?= esc($provisioningUri) ?></code>
        </div>

        <form method="post" action="/admin/security/2fa/enable" class="ck-space-y-6">
            <?= csrf_field() ?>
            <input type="hidden" name="secret" value="<?= esc($secret) ?>">

            <div>
                <label class="ck-block ck-text-sm ck-font-medium ck-text-gray-700 ck-mb-2">Verification code</label>
                <input type="text" name="code" required maxlength="6" inputmode="numeric" autocomplete="one-time-code"
                       class="ck-w-full ck-px-3 ck-py-2 ck-border ck-border-gray-300 ck-rounded-md"
                       placeholder="6-digit code generated by your app">
            </div>

            <div class="ck-flex ck-items-center ck-gap-4">
                <button type="submit" class="ck-px-4 ck-py-2 ck-bg-blue-600 ck-text-white ck-rounded hover:ck-bg-blue-700">Enable 2FA</button>
            </div>
        </form>
    <?php endif; ?>
</div>